POST http://localhost:8080/exam/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "JK123456"
}
###
GET http://localhost:8080/exam/api/info/admin
X-Access-Token:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzQxNDU3MzEsImlhdCI6MTY3NDE0MzkzMSwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.pphgKHRexbngtHiv_Mm8MuRLX5C-6uDSM6xcR5NldB0

###
GET http://localhost:8080/exam/api/info/events
X-Access-Token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjoiYWRtaW4iLCJleHAiOjE2NzQxNDU3MzEsImlhdCI6MTY3NDE0MzkzMSwiaXNzdWVyIjoic2VtZXN0ZXJzdGFydGNvZGUtZGF0MyIsInVzZXJuYW1lIjoiYWRtaW4ifQ.pphgKHRexbngtHiv_Mm8MuRLX5C-6uDSM6xcR5NldB0